import "/images/trucks/truck1.png";

export const links = [
  {
    id: 1,
    linkVal: "/catalog/shtornye-avtomobili",
    content: {
      ru: "Шторные автомобили",
      uz: "Pardali avtomobillar",
      en: "Curtain trucks",
    },
  },
  {
    id: 2,
    linkVal: "/catalog/krany-manipulyatory",
    content: {
      ru: "Краны-манипуляторы",
      uz: "Kran-manipulyatorlar",
      en: "Crane manipulators",
    },
  },
  {
    id: 3,
    linkVal: "/catalog/avtotoplivozapravshchiki",
    content: {
      ru: "Автотопливозаправщики",
      uz: "Yoqilg'i tashuvchilar",
      en: "Fuel tankers",
    },
  },
  {
    id: 4,
    linkVal: "/catalog/avtogidropodyemniki",
    content: {
      ru: "Автогидроподъёмники",
      uz: "Avtogidroko'targichlar",
      en: "Aerial platforms",
    },
  },
  {
    id: 5,
    linkVal: "/catalog/avtotsisterny",
    content: { ru: "Автоцистерны", uz: "Avtosisternalar", en: "Tank trucks" },
  },
  {
    id: 6,
    linkVal: "/catalog/avtoevakuatory",
    content: { ru: "Автоэвакуаторы", uz: "Avtoevakuatorlar", en: "Tow trucks" },
  },
  {
    id: 7,
    linkVal: "/catalog/bortovye-avtomobili",
    content: {
      ru: "Бортовые автомобили",
      uz: "Bortli avtomobillar",
      en: "Flatbed trucks",
    },
  },
  {
    id: 8,
    linkVal: "/catalog/avtofurgony",
    content: {
      ru: "Изотермические фургоны",
      uz: "Izotermik furgonlar",
      en: "Isothermal vans",
    },
  },
  {
    id: 9,
    linkVal: "/catalog/konteynerovozy",
    content: {
      ru: "Контейнеровозы",
      uz: "Konteyner tashuvchilar",
      en: "Container ships",
    },
  },
  {
    id: 10,
    linkVal: "/catalog/kryukovye-pogruzchiki",
    content: {
      ru: "Крюковые погрузчики",
      uz: "Ilmoqli yuklagichlar",
      en: "Hook loaders",
    },
  },
  {
    id: 11,
    linkVal: "/catalog/samosvaly",
    content: { ru: "Самосвалы", uz: "Samosvallar", en: "Dump trucks" },
  },
  {
    id: 12,
    linkVal: "/catalog/avtomobili-dopog-exii",
    content: {
      ru: "Автомобили ДОПОГ категория EXII",
      uz: "DOPOG toifasidagi EXII avtomobillari",
      en: "ADR category EXII vehicles",
    },
  },
];

export const links2 = [
  {
    id: 1,
    linkVal: "/about",
    content: {
      ru: "О компании ООО «Рустрак»",
      uz: '"RusTrak" MChJ haqida',
      en: "About RusTrak LLC",
    },
  },
  {
    id: 2,
    linkVal: "/news",
    content: { ru: "Новости", uz: "Yangiliklar", en: "News" },
  },
  {
    id: 3,
    linkVal: "/partners",
    content: {
      ru: "Наши партнёры",
      uz: "Bizning hamkorlarimiz",
      en: "Our partners",
    },
  },
  {
    id: 4,
    linkVal: "/production",
    content: { ru: "Производство", uz: "Ishlab chiqarish", en: "Production" },
  },
  {
    id: 5,
    linkVal: "/suppliers",
    content: {
      ru: "Поставщикам и партнёрам",
      uz: "Ta'minotchilar va hamkorlar",
      en: "Suppliers and partners",
    },
  },
  {
    id: 6,
    linkVal: "/reviews",
    content: { ru: "Отзывы", uz: "Sharhlar", en: "Reviews" },
  },
  {
    id: 7,
    linkVal: "/cert",
    content: { ru: "Сертификаты", uz: "Sertifikatlar", en: "Certificates" },
  },
  {
    id: 8,
    linkVal: "/vacancies",
    content: { ru: "Вакансии", uz: "Vakansiyalar", en: "Vacancies" },
  },
  {
    id: 9,
    linkVal: "/leasing",
    content: {
      ru: "Кредит и лизинг",
      uz: "Kredit va lizing",
      en: "Credit and leasing",
    },
  },
];

export const links3 = [
  {
    id: 1,
    linkVal: "/photogallery",
    content: { ru: "Фотогалерея", uz: "Fotogalereya", en: "Photo gallery" },
  },
  {
    id: 2,
    linkVal: "/video",
    content: { ru: "Видео", uz: "Видео", en: "Video" },
  },
  {
    id: 3,
    linkVal: "/promo",
    content: {
      ru: "Рекламные материалы",
      uz: "Reklama materiallari",
      en: "Promo materials",
    },
  },
  {
    id: 4,
    linkVal: "/info",
    content: {
      ru: "Информационные материалы",
      uz: "Ma'lumot materiallari",
      en: "Info materials",
    },
  },
];

export const swiperCardTrck = [
  {
    id: 1,
    slug: "shtornye-avtomobili",
    title: {
      ru: "Шторные автомобили",
      uz: "Pardali avtomobillar",
      en: "Curtain trucks",
    },
    quantity: 8,
    img: "/images/trucks/truck10.png",
  },
  {
    id: 2,
    slug: "krany-manipulyatory",
    title: {
      ru: "Краны-манипуляторы",
      uz: "Kran-manipulyatorlar",
      en: "Crane manipulators",
    },
    quantity: 8,
    img: "/images/trucks/truck11.png",
  },
  {
    id: 3,
    slug: "avtotoplivozapravshchiki",
    title: {
      ru: "Автотопливозаправщики",
      uz: "Yoqilg'i tashuvchilar",
      en: "Fuel tankers",
    },
    quantity: 8,
    img: "/images/trucks/truck1.png",
  },
  {
    id: 4,
    slug: "avtogidropodyemniki",
    title: {
      ru: "Автогидроподъёмники",
      uz: "Avtogidroko'targichlar",
      en: "Aerial platforms",
    },
    quantity: 6,
    img: "/images/trucks/truck2.png",
  },
  {
    id: 5,
    slug: "avtotsisterny",
    title: { ru: "Автоцистерны", uz: "Avtosisternalar", en: "Tank trucks" },
    quantity: 7,
    img: "/images/trucks/truck3.png",
  },
  {
    id: 6,
    slug: "avtoevakuatory",
    title: { ru: "Автоэвакуаторы", uz: "Avtoevakuatorlar", en: "Tow trucks" },
    quantity: 6,
    img: "/images/trucks/truck4.png",
  },
  {
    id: 7,
    slug: "bortovye-avtomobili",
    title: {
      ru: "Бортовые автомобили",
      uz: "Bortli avtomobillar",
      en: "Flatbed trucks",
    },
    quantity: 8,
    img: "/images/trucks/truck1.png",
  },
  {
    id: 8,
    slug: "avtofurgony",
    title: {
      ru: "Изотермические фургоны",
      uz: "Izotermik furgonlar",
      en: "Isothermal vans",
    },
    quantity: 8,
    img: "/images/trucks/truck5.png",
  },
  {
    id: 9,
    slug: "konteynerovozy",
    title: {
      ru: "Контейнеровозы",
      uz: "Konteyner tashuvchilar",
      en: "Container ships",
    },
    quantity: 6,
    img: "/images/trucks/truck6.png",
  },
  {
    id: 10,
    slug: "kryukovye-pogruzchiki",
    title: {
      ru: "Крюковые погрузчики",
      uz: "Ilmoqli yuklagichlar",
      en: "Hook loaders",
    },
    quantity: 6,
    img: "/images/trucks/truck7.png",
  },
  {
    id: 11,
    slug: "samosvaly",
    title: { ru: "Самосвалы", uz: "Samosvallar", en: "Dump trucks" },
    quantity: 7,
    img: "/images/trucks/truck8.png",
  },
  {
    id: 12,
    slug: "avtomobili-dopog-exii",
    title: {
      ru: "Автомобили ДОПОГ категория EXII",
      uz: "DOPOG toifasidagi EXII avtomobillari",
      en: "ADR category EXII vehicles",
    },
    quantity: 6,
    img: "/images/trucks/truck9.png",
  },
];

export const recommended_trucks = [
  // ========== SHTORNYE AVTOMOBILI ==========
  {
    id: 9,
    category: "shtornye-avtomobili",
    img: "/images/recommended/008.webp",
    title: { ru: "Шторный грузовик ВАЛДАЙ 12", uz: "Pardali yuk mashinasi ВАЛДАЙ 12", en: "Curtain truck ВАЛДАЙ 12" },
    price: "Цена по запросу",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "8500 x 2500 x 2700 мм",
    payload: "6000",
  },
  {
    id: 10,
    category: "shtornye-avtomobili",
    img: "/images/recommended/009.webp",
    title: { ru: "Шторный грузовик КАМАЗ 65657", uz: "Pardali yuk mashinasi КАМАЗ 65657", en: "Curtain truck КАМАЗ 65657" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "13600 x 2500 x 2700 мм",
    payload: "20000",
  },
  {
    id: 11,
    category: "shtornye-avtomobili",
    img: "/images/recommended/010.webp",
    title: { ru: "Шторный грузовик DONG FENG C120L (модель 5389H2-03)", uz: "Pardali yuk mashinasi DONG FENG C120L", en: "Curtain truck DONG FENG C120L" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "9510 x 2550 x 2550 мм",
    payload: "10000",
  },
  {
    id: 101,
    category: "shtornye-avtomobili",
    img: "/images/recommended/003.webp",
    title: { ru: "Шторный грузовик КАМАЗ 4308 (модель 4389Н2-03)", uz: "Pardali yuk mashinasi КАМАЗ 4308", en: "Curtain truck КАМАЗ 4308" },
    price: "от 5 200 000",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9000 x 2500 x 2700 мм",
    payload: "7000",
  },
  {
    id: 102,
    category: "shtornye-avtomobili",
    img: "/images/recommended/004.webp",
    title: { ru: "Шторный грузовик МАЗ-6312В9 (модель 5391М2-03)", uz: "Pardali yuk mashinasi МАЗ-6312В9", en: "Curtain truck MAZ-6312V9" },
    price: "от 9 800 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "12300 x 2550 x 2700 мм",
    payload: "15000",
  },
  {
    id: 103,
    category: "shtornye-avtomobili",
    img: "/images/recommended/005.webp",
    title: { ru: "Шторный грузовик JAC N200L (модель 4388К2-03)", uz: "Pardali yuk mashinasi JAC N200L", en: "Curtain truck JAC N200L" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "8200 x 2480 x 2620 мм",
    payload: "5500",
  },
  {
    id: 104,
    category: "shtornye-avtomobili",
    img: "/images/recommended/006.webp",
    title: { ru: "Шторный FOTON Aumark S (модель 4384С2-03)", uz: "Pardali FOTON Aumark S", en: "Curtain FOTON Aumark S" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_5_5",
    dimensions: "6200 x 2300 x 2500 мм",
    payload: "3500",
  },
  {
    id: 105,
    category: "shtornye-avtomobili",
    img: "/images/recommended/007.webp",
    title: { ru: "Шторный грузовик КАМАЗ 65117 (модель 5392Н2-03)", uz: "Pardali yuk mashinasi КАМАЗ 65117", en: "Curtain truck КАМАЗ 65117" },
    price: "от 11 500 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "13600 x 2550 x 2700 мм",
    payload: "22000",
  },
  // ========== KRANY-MANIPULYATORY ==========
  {
    id: 1,
    category: "krany-manipulyatory",
    img: "/images/recommended/000.webp",
    title: { ru: "Кран-манипулятор ГАЗ Валдай-18 с КМУ ИНМАН ИМ 240N (модель 438918)", uz: "Kran-manipulyator ГАЗ Валдай-18 KMU INMAN IM 240N bilan", en: "Crane manipulator GAZ Valdai-18 with KMU INMAN IM 240N" },
    price: "Цена по запросу",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "8800 x 2500 x 3200 мм",
    payload: "5000",
  },
  {
    id: 2,
    category: "krany-manipulyatory",
    img: "/images/recommended/001.webp",
    title: { ru: "Кран-манипулятор КАМАЗ 43118 c КМУ ИНМАН ИМ150N (модель 4388С2-10)", uz: "Kran-manipulyator КАМАЗ 43118 KMU INMAN IM150N bilan", en: "Crane manipulator KAMAZ 43118 with KMU INMAN IM150N" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "11000 x 2550 x 3400 мм",
    payload: "18000",
  },
  {
    id: 3,
    category: "krany-manipulyatory",
    img: "/images/recommended/002.webp",
    title: { ru: "Кран-манипулятор JAC N200L c КМУ ИНМАН ИМ150N, ДОПОГ EX II (модель 4389К8-10)", uz: "Kran-manipulyator JAC N200L KMU INMAN IM150N bilan", en: "Crane manipulator JAC N200L with KMU INMAN IM150N" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "9500 x 2500 x 3300 мм",
    payload: "8000",
  },
  {
    id: 5,
    category: "krany-manipulyatory",
    img: "/images/recommended/004.webp",
    title: { ru: "Кран-манипулятор КАМАЗ 65117 с КМУ ИНМАН ИМ 320N (модель 4392С8-10)", uz: "Kran-manipulyator КАМАЗ 65117 KMU INMAN IM 320N bilan", en: "Crane manipulator KAMAZ 65117 with KMU INMAN IM 320N" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "12200 x 2550 x 3500 мм",
    payload: "20000",
  },
  {
    id: 106,
    category: "krany-manipulyatory",
    img: "/images/recommended/011.webp",
    title: { ru: "Кран-манипулятор МАЗ-631208 с КМУ ИМ 180N (модель 4391М8-10)", uz: "Kran-manipulyator МАЗ-631208 KMU IM 180N bilan", en: "Crane manipulator MAZ-631208 with KMU IM 180N" },
    price: "от 14 200 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "11800 x 2550 x 3500 мм",
    payload: "22000",
  },
  {
    id: 107,
    category: "krany-manipulyatory",
    img: "/images/recommended/012.webp",
    title: { ru: "Кран-манипулятор FOTON Auman ETX на базе КМУ ИМ 120N (модель 4386F8-10)", uz: "Kran-manipulyator FOTON Auman ETX KMU IM 120N asosida", en: "Crane manipulator FOTON Auman ETX with KMU IM 120N" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_20",
    dimensions: "10500 x 2500 x 3400 мм",
    payload: "12000",
  },
  {
    id: 108,
    category: "krany-manipulyatory",
    img: "/images/recommended/000.webp",
    title: { ru: "Кран-манипулятор DONG FENG DFL3251 с КМУ ИМ 200N (модель 4390D8-10)", uz: "Kran-manipulyator DONG FENG DFL3251 KMU IM 200N bilan", en: "Crane manipulator DONG FENG DFL3251 with KMU IM 200N" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "10800 x 2550 x 3450 мм",
    payload: "14000",
  },
  {
    id: 109,
    category: "krany-manipulyatory",
    img: "/images/recommended/001.webp",
    title: { ru: "Кран-манипулятор DAEWOO Novus с КМУ ИМ 100N (модель 4385W8-10)", uz: "Kran-manipulyator DAEWOO Novus KMU IM 100N bilan", en: "Crane manipulator DAEWOO Novus with KMU IM 100N" },
    price: "от 9 500 000",
    brand: "DAEWOO",
    mass: "do_20",
    dimensions: "10200 x 2550 x 3350 мм",
    payload: "12500",
  },
  // ========== AVTOTOPLIVOZAPRAVSHCHIKI ==========
  {
    id: 6,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/005.webp",
    title: { ru: "Автотопливозаправщик JAC N200 АТЗ-10 м³", uz: "Yoqilg'i tashuvchi JAC N200 АТЗ-10 м³", en: "Fuel tanker JAC N200 ATZ-10 m³" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "9000 x 2500 x 3000 мм",
    payload: "8000",
  },
  {
    id: 7,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/006.webp",
    title: { ru: "Топливозаправщик ГАЗ Садко 9 с АТЗ 4,5 м³ двухсекционная", uz: "Yoqilg'i tashuvchi ГАЗ Садко 9 АТЗ 4,5 м³ ikki bo'limli", en: "Fuel tanker GAZ Sadko 9 with ATZ 4.5 m³ two-section" },
    price: "от 8 800 000",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "7800 x 2450 x 2900 мм",
    payload: "5000",
  },
  {
    id: 8,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/007.webp",
    title: { ru: "Топливозаправщик ГАЗ Валдай 12 АТЗ 8 м³", uz: "Yoqilg'i tashuvchi ГАЗ Валдай 12 АТЗ 8 м³", en: "Fuel tanker GAZ Valdai 12 ATZ 8 m³" },
    price: "от 7 850 000",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "8800 x 2500 x 3100 мм",
    payload: "7000",
  },
  {
    id: 110,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/008.webp",
    title: { ru: "Автотопливозаправщик КАМАЗ 43118 АТЗ-16 м³", uz: "Yoqilg'i tashuvchi КАМАЗ 43118 АТЗ-16 м³", en: "Fuel tanker KAMAZ 43118 ATZ-16 m³" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "11200 x 2550 x 3300 мм",
    payload: "17000",
  },
  {
    id: 111,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/009.webp",
    title: { ru: "Автотопливозаправщик МАЗ-631208 АТЗ-20 м³", uz: "Yoqilg'i tashuvchi МАЗ-631208 АТЗ-20 м³", en: "Fuel tanker MAZ-631208 ATZ-20 m³" },
    price: "от 15 600 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "11800 x 2550 x 3400 мм",
    payload: "20000",
  },
  {
    id: 112,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/010.webp",
    title: { ru: "Топливозаправщик FOTON Auman АТЗ-12 м³ (модель 4388F0-06)", uz: "Yoqilg'i tashuvchi FOTON Auman АТЗ-12 м³", en: "Fuel tanker FOTON Auman ATZ-12 m³" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_20",
    dimensions: "10200 x 2500 x 3200 мм",
    payload: "11000",
  },
  // ========== AVTOGIDROPODYEMNIKI ==========
  {
    id: 13,
    category: "avtogidropodyemniki",
    img: "/images/recommended/012.webp",
    title: { ru: "Автогидроподъемник PALFINGER P 180Т на шасси ГАЗ C41R33", uz: "Avtogidroko'targich PALFINGER P 180Т ГАЗ C41R33 shassi asosida", en: "Aerial platform PALFINGER P 180T on GAZ C41R33 chassis" },
    price: "Цена по запросу",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "9000 x 2500 x 3200 мм",
    payload: "6000",
  },
  {
    id: 113,
    category: "avtogidropodyemniki",
    img: "/images/recommended/011.webp",
    title: { ru: "Автогидроподъемник АГП-22 на шасси КАМАЗ 43253", uz: "Avtogidroko'targich АГП-22 КАМАЗ 43253 shassi asosida", en: "Aerial platform AGP-22 on KAMAZ 43253 chassis" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "do_20",
    dimensions: "10500 x 2550 x 3800 мм",
    payload: "12000",
  },
  {
    id: 114,
    category: "avtogidropodyemniki",
    img: "/images/recommended/010.webp",
    title: { ru: "Автогидроподъемник АГП-30 на шасси МАЗ-533702", uz: "Avtogidroko'targich АГП-30 МАЗ-533702 shassi asosida", en: "Aerial platform AGP-30 on MAZ-533702 chassis" },
    price: "от 12 500 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "11200 x 2550 x 4000 мм",
    payload: "14000",
  },
  {
    id: 115,
    category: "avtogidropodyemniki",
    img: "/images/recommended/009.webp",
    title: { ru: "Автогидроподъемник АГП-36 на шасси КАМАЗ 65117", uz: "Avtogidroko'targich АГП-36 КАМАЗ 65117 shassi asosida", en: "Aerial platform AGP-36 on KAMAZ 65117 chassis" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "12000 x 2550 x 4200 мм",
    payload: "20000",
  },
  // ========== AVTOTSISTERNY ==========
  {
    id: 116,
    category: "avtotsisterny",
    img: "/images/recommended/000.webp",
    title: { ru: "Автоцистерна ГАЗ-C41R33 АЦ-5,5 (модель 4787Г0-09)", uz: "Avtosisterna ГАЗ-C41R33 АЦ-5,5", en: "Tank truck GAZ-C41R33 AC-5.5" },
    price: "от 5 900 000",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "8500 x 2500 x 3000 мм",
    payload: "6000",
  },
  {
    id: 117,
    category: "avtotsisterny",
    img: "/images/recommended/001.webp",
    title: { ru: "Автоцистерна КАМАЗ 43118 АЦ-12 (модель 4787К0-09)", uz: "Avtosisterna КАМАЗ 43118 АЦ-12", en: "Tank truck KAMAZ 43118 AC-12" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "11200 x 2550 x 3400 мм",
    payload: "17000",
  },
  {
    id: 118,
    category: "avtotsisterny",
    img: "/images/recommended/002.webp",
    title: { ru: "Автоцистерна МАЗ-630308 АЦ-18 (модель 4787М0-09)", uz: "Avtosisterna МАЗ-630308 АЦ-18", en: "Tank truck MAZ-630308 AC-18" },
    price: "от 16 800 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "11800 x 2550 x 3500 мм",
    payload: "22000",
  },
  {
    id: 119,
    category: "avtotsisterny",
    img: "/images/recommended/003.webp",
    title: { ru: "Автоцистерна JAC N200 АЦ-7 (модель 4786J0-09)", uz: "Avtosisterna JAC N200 АЦ-7", en: "Tank truck JAC N200 AC-7" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "9000 x 2500 x 3100 мм",
    payload: "8000",
  },
  {
    id: 120,
    category: "avtotsisterny",
    img: "/images/recommended/004.webp",
    title: { ru: "Автоцистерна FOTON Auman АЦ-10 (модель 4788F0-09)", uz: "Avtosisterna FOTON Auman АЦ-10", en: "Tank truck FOTON Auman AC-10" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_20",
    dimensions: "10200 x 2500 x 3200 мм",
    payload: "12000",
  },
  // ========== AVTOEVAKUATORY ==========
  {
    id: 121,
    category: "avtoevakuatory",
    img: "/images/recommended/005.webp",
    title: { ru: "Эвакуатор ГАЗ-3302 с ломаной платформой (модель 4789Г2-07)", uz: "Evakuator ГАЗ-3302 siniq platforma bilan", en: "Tow truck GAZ-3302 with broken platform" },
    price: "от 3 500 000",
    brand: "ГАЗ",
    mass: "do_5_5",
    dimensions: "6800 x 2300 x 2600 мм",
    payload: "3000",
  },
  {
    id: 122,
    category: "avtoevakuatory",
    img: "/images/recommended/006.webp",
    title: { ru: "Эвакуатор КАМАЗ 4308 с частичной погрузкой (модель 4789К2-07)", uz: "Evakuator КАМАЗ 4308 qisman yuklash bilan", en: "Tow truck KAMAZ 4308 with partial loading" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9000 x 2500 x 3000 мм",
    payload: "7000",
  },
  {
    id: 123,
    category: "avtoevakuatory",
    img: "/images/recommended/007.webp",
    title: { ru: "Эвакуатор JAC N200 сдвижная платформа (модель 4789J2-07)", uz: "Evakuator JAC N200 siljuvchi platforma", en: "Tow truck JAC N200 sliding platform" },
    price: "от 4 200 000",
    brand: "JAC",
    mass: "do_5_5",
    dimensions: "7200 x 2450 x 2700 мм",
    payload: "4000",
  },
  // ========== BORTOVYE AVTOMOBILI ==========
  {
    id: 124,
    category: "bortovye-avtomobili",
    img: "/images/recommended/008.webp",
    title: { ru: "Бортовой автомобиль ГАЗ Садко Next С41R23 (модель 4783Г2-04)", uz: "Bortli avtomobil ГАЗ Садко Next С41R23", en: "Flatbed truck GAZ Sadko Next C41R23" },
    price: "от 4 200 000",
    brand: "ГАЗ",
    mass: "do_5_5",
    dimensions: "6800 x 2300 x 2500 мм",
    payload: "3500",
  },
  {
    id: 125,
    category: "bortovye-avtomobili",
    img: "/images/recommended/009.webp",
    title: { ru: "Бортовой автомобиль КАМАЗ 43253 (модель 4784К2-04)", uz: "Bortli avtomobil КАМАЗ 43253", en: "Flatbed truck KAMAZ 43253" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9200 x 2500 x 2700 мм",
    payload: "8000",
  },
  {
    id: 126,
    category: "bortovye-avtomobili",
    img: "/images/recommended/010.webp",
    title: { ru: "Бортовой автомобиль МАЗ-6312В9 (модель 4785М2-04)", uz: "Bortli avtomobil МАЗ-6312В9", en: "Flatbed truck MAZ-6312V9" },
    price: "от 10 500 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "12300 x 2550 x 2800 мм",
    payload: "16000",
  },
  {
    id: 127,
    category: "bortovye-avtomobili",
    img: "/images/recommended/011.webp",
    title: { ru: "Бортовой автомобиль JAC N200L (модель 4782J2-04)", uz: "Bortli avtomobil JAC N200L", en: "Flatbed truck JAC N200L" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "8800 x 2480 x 2650 мм",
    payload: "6500",
  },
  {
    id: 128,
    category: "bortovye-avtomobili",
    img: "/images/recommended/012.webp",
    title: { ru: "Бортовой автомобиль КАМАЗ 65117 (модель 4786К2-04)", uz: "Bortli avtomobil КАМАЗ 65117", en: "Flatbed truck KAMAZ 65117" },
    price: "от 12 800 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "13600 x 2550 x 2900 мм",
    payload: "22000",
  },
  {
    id: 129,
    category: "bortovye-avtomobili",
    img: "/images/recommended/000.webp",
    title: { ru: "Бортовой автомобиль FOTON Auman (модель 4787F2-04)", uz: "Bortli avtomobil FOTON Auman", en: "Flatbed truck FOTON Auman" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_20",
    dimensions: "10800 x 2500 x 2750 мм",
    payload: "13000",
  },
  // ========== AVTOFURGONY ==========
  {
    id: 130,
    category: "avtofurgony",
    img: "/images/recommended/001.webp",
    title: { ru: "Изотермический фургон ГАЗ Газель Next (модель 4784Г2-05)", uz: "Izotermik furgo ГАЗ Газель Next", en: "Isothermal van GAZ Gazelle Next" },
    price: "от 3 800 000",
    brand: "ГАЗ",
    mass: "do_5_5",
    dimensions: "6200 x 2200 x 2500 мм",
    payload: "2500",
  },
  {
    id: 131,
    category: "avtofurgony",
    img: "/images/recommended/002.webp",
    title: { ru: "Изотермический фургон КАМАЗ 4308 (модель 4785К2-05)", uz: "Izotermik furgo КАМАЗ 4308", en: "Isothermal van KAMAZ 4308" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9000 x 2500 x 2800 мм",
    payload: "7500",
  },
  {
    id: 132,
    category: "avtofurgony",
    img: "/images/recommended/003.webp",
    title: { ru: "Изотермический фургон МАЗ-6312 (модель 4786М2-05)", uz: "Izotermik furgo МАЗ-6312", en: "Isothermal van MAZ-6312" },
    price: "от 11 200 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "12300 x 2550 x 2900 мм",
    payload: "15000",
  },
  {
    id: 133,
    category: "avtofurgony",
    img: "/images/recommended/004.webp",
    title: { ru: "Изотермический фургон JAC N200 (модель 4783J2-05)", uz: "Izotermik furgo JAC N200", en: "Isothermal van JAC N200" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "8500 x 2450 x 2700 мм",
    payload: "5500",
  },
  {
    id: 134,
    category: "avtofurgony",
    img: "/images/recommended/005.webp",
    title: { ru: "Изотермический фургон FOTON Aumark (модель 4784F2-05)", uz: "Izotermik furgo FOTON Aumark", en: "Isothermal van FOTON Aumark" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_5_5",
    dimensions: "6800 x 2300 x 2600 мм",
    payload: "3000",
  },
  // ========== KONTEYNEROVOZY ==========
  {
    id: 135,
    category: "konteynerovozy",
    img: "/images/recommended/006.webp",
    title: { ru: "Контейнеровоз КАМАЗ 65117 20-фут (модель 4789К2-08)", uz: "Konteyner tashuvchi КАМАЗ 65117 20-fut", en: "Container truck KAMAZ 65117 20-ft" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "12200 x 2550 x 2900 мм",
    payload: "20000",
  },
  {
    id: 136,
    category: "konteynerovozy",
    img: "/images/recommended/007.webp",
    title: { ru: "Контейнеровоз МАЗ-630308 40-фут (модель 4790М2-08)", uz: "Konteyner tashuvchi МАЗ-630308 40-fut", en: "Container truck MAZ-630308 40-ft" },
    price: "от 18 500 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "13600 x 2550 x 3000 мм",
    payload: "24000",
  },
  {
    id: 137,
    category: "konteynerovozy",
    img: "/images/recommended/008.webp",
    title: { ru: "Контейнеровоз КАМАЗ 65658 (модель 4791К2-08)", uz: "Konteyner tashuvchi КАМАЗ 65658", en: "Container truck KAMAZ 65658" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "13400 x 2550 x 2950 мм",
    payload: "22000",
  },
  // ========== KRYUKOVYE POGRUZCHIKI ==========
  {
    id: 138,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/009.webp",
    title: { ru: "Крюковой погрузчик КАМАЗ 43118 (модель 4790К2-11)", uz: "Ilmoqli yuklagich КАМАЗ 43118", en: "Hook loader KAMAZ 43118" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "11200 x 2550 x 3200 мм",
    payload: "18000",
  },
  {
    id: 139,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/010.webp",
    title: { ru: "Крюковой погрузчик МАЗ-631208 (модель 4791М2-11)", uz: "Ilmoqli yuklagich МАЗ-631208", en: "Hook loader MAZ-631208" },
    price: "от 14 800 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "11800 x 2550 x 3300 мм",
    payload: "22000",
  },
  {
    id: 140,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/011.webp",
    title: { ru: "Крюковой погрузчик DONG FENG DFL3251 (модель 4789D2-11)", uz: "Ilmoqli yuklagich DONG FENG DFL3251", en: "Hook loader DONG FENG DFL3251" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "10800 x 2550 x 3100 мм",
    payload: "14000",
  },
  // ========== SAMOSVALY ==========
  {
    id: 12,
    category: "samosvaly",
    img: "/images/recommended/011.webp",
    title: { ru: "Самосвал на шасси КОМПАС 9 (модель 4789Г2-12)", uz: "Samosval КОМПАС 9 shassi asosida", en: "Dump truck on KOMPAS 9 chassis" },
    price: "Цена по запросу",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "9500 x 2500 x 3000 мм",
    payload: "8500",
  },
  {
    id: 141,
    category: "samosvaly",
    img: "/images/recommended/012.webp",
    title: { ru: "Самосвал КАМАЗ 43255 (модель 4790К2-12)", uz: "Samosval КАМАЗ 43255", en: "Dump truck KAMAZ 43255" },
    price: "от 9 200 000",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9800 x 2550 x 3300 мм",
    payload: "10000",
  },
  {
    id: 142,
    category: "samosvaly",
    img: "/images/recommended/000.webp",
    title: { ru: "Самосвал МАЗ-6516В8 (модель 4791М2-12)", uz: "Samosval МАЗ-6516В8", en: "Dump truck MAZ-6516V8" },
    price: "от 13 500 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "10800 x 2550 x 3600 мм",
    payload: "20000",
  },
  {
    id: 143,
    category: "samosvaly",
    img: "/images/recommended/001.webp",
    title: { ru: "Самосвал DONG FENG DFL3251 (модель 4788D2-12)", uz: "Samosval DONG FENG DFL3251", en: "Dump truck DONG FENG DFL3251" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "10500 x 2550 x 3400 мм",
    payload: "14000",
  },
  {
    id: 144,
    category: "samosvaly",
    img: "/images/recommended/002.webp",
    title: { ru: "Самосвал JAC N200 (модель 4786J2-12)", uz: "Samosval JAC N200", en: "Dump truck JAC N200" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "9200 x 2480 x 3100 мм",
    payload: "8000",
  },
  // ========== AVTOMOBILI DOPOG EXII ==========
  {
    id: 4,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/003.webp",
    title: { ru: "Шторный грузовик КАМАЗ 4308 ДОПОГ ЕХII (модель 4388Н2-10)", uz: "Pardali yuk mashinasi КАМАЗ 4308 ДОПОГ ЕХII", en: "Curtain truck КАМАЗ 4308 ADR EXII" },
    price: "Цена по запросу",
    brand: "КАМАЗ",
    mass: "do_12",
    dimensions: "9510 x 2550 x 2550 мм",
    payload: "6340",
  },
  {
    id: 145,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/004.webp",
    title: { ru: "Автомобиль ДОПОГ ГАЗ Валдай 18 (модель 4387Г2-10)", uz: "ДОПОГ avtomobili ГАЗ Валдай 18", en: "ADR vehicle GAZ Valdai 18" },
    price: "Цена по запросу",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "8800 x 2500 x 2700 мм",
    payload: "5500",
  },
  {
    id: 146,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/005.webp",
    title: { ru: "Автомобиль ДОПОГ МАЗ-533702 (модель 4389М2-10)", uz: "ДОПОГ avtomobili МАЗ-533702", en: "ADR vehicle MAZ-533702" },
    price: "от 9 800 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "10800 x 2550 x 2800 мм",
    payload: "12000",
  },
  {
    id: 147,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/006.webp",
    title: { ru: "Автомобиль ДОПОГ JAC N200L (модель 4388J2-10)", uz: "ДОПОГ avtomobili JAC N200L", en: "ADR vehicle JAC N200L" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_12",
    dimensions: "9200 x 2480 x 2650 мм",
    payload: "7000",
  },
,
  // --- Qo'shimcha avtofurgony ---
  {
    id: 151,
    category: "avtofurgony",
    img: "/images/recommended/003.webp",
    title: { ru: "Изотермический фургон КАМАЗ 65117 (модель 4786К2-05)", uz: "Izotermik furgon KAMAZ 65117", en: "Isothermal van KAMAZ 65117" },
    price: "от 12 500 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "9500 x 2550 x 2700 мм",
    payload: "14000",
  },
  {
    id: 152,
    category: "avtofurgony",
    img: "/images/recommended/010.webp",
    title: { ru: "Изотермический фургон DONG FENG C120L (модель 4787D2-05)", uz: "Izotermik furgon DONG FENG C120L", en: "Isothermal van DONG FENG C120L" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "8200 x 2500 x 2600 мм",
    payload: "8000",
  },
  {
    id: 153,
    category: "avtofurgony",
    img: "/images/recommended/006.webp",
    title: { ru: "Изотермический фургон DAEWOO Novus (модель 4788W2-05)", uz: "Izotermik furgon DAEWOO Novus", en: "Isothermal van DAEWOO Novus" },
    price: "Цена по запросу",
    brand: "DAEWOO",
    mass: "do_20",
    dimensions: "9200 x 2550 x 2650 мм",
    payload: "11000",
  },

  // --- Qo'shimcha avtoevakuatory ---
  {
    id: 154,
    category: "avtoevakuatory",
    img: "/images/recommended/004.webp",
    title: { ru: "Эвакуатор МАЗ-4371 с прямой платформой (модель 4789М2-07)", uz: "Evakuator MAZ-4371 to'g'ri platforma", en: "Tow truck MAZ-4371 flat platform" },
    price: "от 6 100 000",
    brand: "МАЗ",
    mass: "do_12",
    dimensions: "7800 x 2400 x 2500 мм",
    payload: "4500",
  },
  {
    id: 155,
    category: "avtoevakuatory",
    img: "/images/recommended/005.webp",
    title: { ru: "Эвакуатор FOTON Aumark C (модель 4789F2-07)", uz: "Evakuator FOTON Aumark C", en: "Tow truck FOTON Aumark C" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_12",
    dimensions: "7500 x 2350 x 2450 мм",
    payload: "4000",
  },
  {
    id: 156,
    category: "avtoevakuatory",
    img: "/images/recommended/008.webp",
    title: { ru: "Эвакуатор DONG FENG Captain-T (модель 4789D2-07)", uz: "Evakuator DONG FENG Captain-T", en: "Tow truck DONG FENG Captain-T" },
    price: "от 3 900 000",
    brand: "DONG FENG",
    mass: "do_5_5",
    dimensions: "6200 x 2200 x 2300 мм",
    payload: "2500",
  },

  // --- Qo'shimcha konteynerovozy ---
  {
    id: 157,
    category: "konteynerovozy",
    img: "/images/recommended/004.webp",
    title: { ru: "Контейнеровоз МАЗ-6430В9 (модель 4792М2-08)", uz: "Konteyner tashuvchi MAZ-6430В9", en: "Container truck MAZ-6430V9" },
    price: "от 11 800 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "12500 x 2500 x 3600 мм",
    payload: "32000",
  },
  {
    id: 158,
    category: "konteynerovozy",
    img: "/images/recommended/001.webp",
    title: { ru: "Контейнеровоз JAC K7 (модель 4793J2-08)", uz: "Konteyner tashuvchi JAC K7", en: "Container truck JAC K7" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "svyshe_20",
    dimensions: "12600 x 2550 x 3800 мм",
    payload: "30000",
  },
  {
    id: 159,
    category: "konteynerovozy",
    img: "/images/recommended/005.webp",
    title: { ru: "Контейнеровоз FOTON Auman EST A (модель 4794F2-08)", uz: "Konteyner tashuvchi FOTON Auman EST A", en: "Container truck FOTON Auman EST A" },
    price: "от 13 200 000",
    brand: "FOTON",
    mass: "svyshe_20",
    dimensions: "12500 x 2500 x 3750 мм",
    payload: "31000",
  },

  // --- Qo'shimcha kryukovye-pogruzchiki ---
  {
    id: 160,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/008.webp",
    title: { ru: "Крюковой погрузчик ГАЗ Валдай 18 (модель 4792Г2-11)", uz: "Ilmoqli yuklagich GAZ Valday 18", en: "Hook loader GAZ Valday 18" },
    price: "от 7 500 000",
    brand: "ГАЗ",
    mass: "do_20",
    dimensions: "8200 x 2500 x 2900 мм",
    payload: "10000",
  },
  {
    id: 161,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/001.webp",
    title: { ru: "Крюковой погрузчик JAC N200 (модель 4793J2-11)", uz: "Ilmoqli yuklagich JAC N200", en: "Hook loader JAC N200" },
    price: "Цена по запросу",
    brand: "JAC",
    mass: "do_20",
    dimensions: "8500 x 2550 x 3000 мм",
    payload: "12000",
  },
  {
    id: 162,
    category: "kryukovye-pogruzchiki",
    img: "/images/recommended/003.webp",
    title: { ru: "Крюковой погрузчик КАМАЗ 6520 (модель 4794К2-11)", uz: "Ilmoqli yuklagich KAMAZ 6520", en: "Hook loader KAMAZ 6520" },
    price: "от 11 000 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "8900 x 2550 x 3200 мм",
    payload: "20000",
  },

  // --- Qo'shimcha avtogidropodyemniki ---
  {
    id: 163,
    category: "avtogidropodyemniki",
    img: "/images/recommended/001.webp",
    title: { ru: "Автогидроподъемник АГП-28 на шасси JAC N120", uz: "Avtogidroko'targich AGP-28 JAC N120", en: "Aerial platform AGP-28 on JAC N120" },
    price: "от 8 900 000",
    brand: "JAC",
    mass: "do_12",
    dimensions: "8200 x 2500 x 3400 мм",
    payload: "400",
  },
  {
    id: 164,
    category: "avtogidropodyemniki",
    img: "/images/recommended/008.webp",
    title: { ru: "Автогидроподъемник АГП-18 на шасси ГАЗ Садко Next", uz: "Avtogidroko'targich AGP-18 GAZ Sadko Next", en: "Aerial platform AGP-18 on GAZ Sadko Next" },
    price: "от 6 400 000",
    brand: "ГАЗ",
    mass: "do_12",
    dimensions: "7500 x 2400 x 3200 мм",
    payload: "300",
  },

  // --- Qo'shimcha avtomobili-dopog-exii ---
  {
    id: 165,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/005.webp",
    title: { ru: "Автомобиль ДОПОГ FOTON Aumark EXII (модель 4386F2-10)", uz: "DOPOG avtomobili FOTON Aumark EXII", en: "ADR vehicle FOTON Aumark EXII" },
    price: "Цена по запросу",
    brand: "FOTON",
    mass: "do_12",
    dimensions: "7800 x 2450 x 2600 мм",
    payload: "6000",
  },
  {
    id: 166,
    category: "avtomobili-dopog-exii",
    img: "/images/recommended/003.webp",
    title: { ru: "Автомобиль ДОПОГ КАМАЗ 65117 EXII (модель 4385К2-10)", uz: "DOPOG avtomobili KAMAZ 65117 EXII", en: "ADR vehicle KAMAZ 65117 EXII" },
    price: "от 10 900 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "9800 x 2550 x 2750 мм",
    payload: "14000",
  },

  // --- Qo'shimcha samosvaly ---
  {
    id: 167,
    category: "samosvaly",
    img: "/images/recommended/003.webp",
    title: { ru: "Самосвал КАМАЗ 6520 (модель 4792К2-12)", uz: "Samosval KAMAZ 6520", en: "Dump truck KAMAZ 6520" },
    price: "от 9 800 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "7800 x 2500 x 3050 мм",
    payload: "20000",
  },
  {
    id: 168,
    category: "samosvaly",
    img: "/images/recommended/004.webp",
    title: { ru: "Самосвал МАЗ-6501С9 (модель 4793М2-12)", uz: "Samosval MAZ-6501S9", en: "Dump truck MAZ-6501S9" },
    price: "от 8 700 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "7600 x 2550 x 3000 мм",
    payload: "19000",
  },

  // --- Qo'shimcha avtotsisterny ---
  {
    id: 169,
    category: "avtotsisterny",
    img: "/images/recommended/003.webp",
    title: { ru: "Автоцистерна КАМАЗ 65115 АЦ-15 (модель 4785К0-09)", uz: "Avtosisterna KAMAZ 65115 ATS-15", en: "Tank truck KAMAZ 65115 AC-15" },
    price: "от 9 200 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "8500 x 2500 x 3100 мм",
    payload: "15000",
  },
  {
    id: 170,
    category: "avtotsisterny",
    img: "/images/recommended/004.webp",
    title: { ru: "Автоцистерна МАЗ-6312В9 АЦ-20 (модель 4786М0-09)", uz: "Avtosisterna MAZ-6312V9 ATS-20", en: "Tank truck MAZ-6312V9 AC-20" },
    price: "от 10 500 000",
    brand: "МАЗ",
    mass: "svyshe_20",
    dimensions: "9200 x 2550 x 3200 мм",
    payload: "20000",
  },

  // --- Qo'shimcha bortovye-avtomobili ---
  {
    id: 171,
    category: "bortovye-avtomobili",
    img: "/images/recommended/010.webp",
    title: { ru: "Бортовой автомобиль DONG FENG C120L (модель 4788D2-04)", uz: "Bortli avtomobil DONG FENG C120L", en: "Flatbed truck DONG FENG C120L" },
    price: "от 5 800 000",
    brand: "DONG FENG",
    mass: "do_12",
    dimensions: "8200 x 2500 x 2400 мм",
    payload: "7000",
  },
  {
    id: 172,
    category: "bortovye-avtomobili",
    img: "/images/recommended/004.webp",
    title: { ru: "Бортовой автомобиль МАЗ-5340 (модель 4789М2-04)", uz: "Bortli avtomobil MAZ-5340", en: "Flatbed truck MAZ-5340" },
    price: "от 7 200 000",
    brand: "МАЗ",
    mass: "do_20",
    dimensions: "8600 x 2550 x 2500 мм",
    payload: "10000",
  },

  // --- Qo'shimcha avtotoplivozapravshchiki ---
  {
    id: 173,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/003.webp",
    title: { ru: "Топливозаправщик КАМАЗ 65115 АТЗ-14", uz: "Yoqilg'i quyuvchi KAMAZ 65115 ATZ-14", en: "Fuel tanker KAMAZ 65115 ATZ-14" },
    price: "от 9 700 000",
    brand: "КАМАЗ",
    mass: "svyshe_20",
    dimensions: "8500 x 2500 x 3150 мм",
    payload: "14000",
  },
  {
    id: 174,
    category: "avtotoplivozapravshchiki",
    img: "/images/recommended/010.webp",
    title: { ru: "Топливозаправщик DONG FENG DFL АТЗ-10", uz: "Yoqilg'i quyuvchi DONG FENG DFL ATZ-10", en: "Fuel tanker DONG FENG DFL ATZ-10" },
    price: "Цена по запросу",
    brand: "DONG FENG",
    mass: "do_20",
    dimensions: "8200 x 2500 x 3000 мм",
    payload: "10000",
  },
];
export const news = [
  {
    id: 1,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 2,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 3,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 4,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 5,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 6,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 7,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
  {
    id: 8,
    img: "/images/recommended/000.webp",
    date: "01.01.2026",
    title: {
      ru: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      uz: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
      en: "Первый в России контейнеровоз на шасси КАМАЗ‑65658 выпустил «Рустрак»",
    },
  },
];

export const aboutSliderData = [
  {
    id: 1,
    icon: "/images/smthing_drill.svg",
    title: {
      ru: "Собственная производственная база",
      uz: "O'z ishlab chiqarish bazasi",
      en: "Own production base",
    },
    text: {
      ru: "позволяет максимально снизить себестоимость продукции, повышая её конкурентоспособность",
      uz: "mahsulot tannarxini maksimal darajada kamaytirish imkonini beradi, uning raqobatbardoshligini oshiradi",
      en: "allows to minimize the cost of production, increasing its competitiveness",
    },
  },
  {
    id: 2,
    icon: "/images/todo_list.svg",
    title: {
      ru: "Отдел контроля качества",
      uz: "Sifat nazorati bo'limi",
      en: "Quality control department",
    },
    text: {
      ru: "проверяет каждую единицу спецтехники, что гарантирует длительный срок эксплуатации и безотказную работу техники.",
      uz: "har bir maxsus texnika uskunasini tekshiradi, bu uzoq xizmat muddatini va texnikaning nosozliksiz ishlashini kafolatlaydi.",
      en: "checks each unit of special equipment, which guarantees a long service life and trouble-free operation of the equipment.",
    },
  },
  {
    id: 3,
    icon: "/images/lil_car.svg",
    title: {
      ru: "Разработка надстроек шасси",
      uz: "Shassi ustki qurilmalarini ishlab chiqish",
      en: "Development of chassis superstructures",
    },
    text: {
      ru: "производится на шасси мировых — надёжную в эксплуатации и максимально адаптированную под конкретные условия работы.",
      uz: "jahon shassilarida ishlab chiqariladi - foydalanishda ishonchli va muayyan ish sharoitlariga maksimal darajada moslashtirilgan.",
      en: "is produced on the chassis of the world - reliable in operation and maximally adapted to specific working conditions.",
    },
  },
  {
    id: 4,
    icon: "/images/drawing.svg",
    title: {
      ru: "Наличие конструкторского бюро",
      uz: "Dizayn byurosining mavjudligi",
      en: "Presence of a design bureau",
    },
    text: {
      ru: "обеспечивает возможность индивидуального подхода к каждому клиенту.",
      uz: "har bir mijozga individual yondashish imkoniyatini ta'minlaydi.",
      en: "provides the possibility of an individual approach to each client.",
    },
  },
  {
    id: 5,
    icon: "/images/delivery_car.svg",
    title: {
      ru: "Собственная служба логистики",
      uz: "O'z logistika xizmati",
      en: "Own logistics service",
    },
    text: {
      ru: "предельно уменьшает сроки доставки комплектующих и агрегатов.",
      uz: "butlovchi qismlar va agregatlarni yetkazib berish vaqtini sezilarli darajada qisqartiradi.",
      en: "extremely reduces the delivery time of components and assemblies.",
    },
  },
  {
    id: 6,
    icon: "/images/wrenchs.svg",
    title: {
      ru: "Сервисная партнёрская сеть",
      uz: "Xizmat ko'rsatish hamkor tarmog'i",
      en: "Service partner network",
    },
    text: {
      ru: "гарантирует техническую помощь на всей территории РФ.",
      uz: "Rossiya Federatsiyasi hududida texnik yordam kafolatlanadi.",
      en: "guarantees technical assistance throughout the Russian Federation.",
    },
  },
];

export const aboutRustrakThis = [
  {
    text: {
      ru: "3 производственных корпуса, общей площадью более 7000 м2;",
      uz: "Umumiy maydoni 7000 m2 dan ortiq bo'lgan 3 ta ishlab chiqarish binosi;",
      en: "3 production buildings with a total area of more than 7000 m2;",
    },
  },
  {
    text: {
      ru: "производственная территория более 20000 м2;",
      uz: "20000 m2 dan ortiq ishlab chiqarish hududi;",
      en: "production area of more than 20000 m2;",
    },
  },
  {
    text: {
      ru: "служба качества, гарантирующая выпуск высококачественной техники;",
      uz: "Yuqori sifatli uskunalar ishlab chiqarishni kafolatlaydigan sifat xizmati;",
      en: "quality service that guarantees the release of high-quality equipment;",
    },
  },
  {
    text: {
      ru: "современный парк станочного оборудования;",
      uz: "Zamonaviy dastgohlar parki;",
      en: "modern park of machine tools;",
    },
  },
  {
    text: {
      ru: "ежемесячный объём выпускаемой техники - до 110 единиц;",
      uz: "Ishlab chiqarilgan uskunaning oylik hajmi - 110 donagacha;",
      en: "monthly volume of manufactured equipment - up to 110 units;",
    },
  },
  {
    text: {
      ru: "наличие собственной конструкторско-технологической службы.",
      uz: "O'zining dizayn va texnologik xizmatining mavjudligi.",
      en: "the presence of its own design and technological service.",
    },
  },
];

export const rtrfContacts = [
  {
    fullName: {
      ru: "Шаронов Сергей Владимирович",
      uz: "Sharonov Sergey Vladimirovich",
      en: "Sharonov Sergey Vladimirovich",
    },
    position: {
      ru: "Генеральный директор",
      uz: "Bosh direktor",
      en: "General Director",
    },
    phone: "8 (831) 225-00-55",
    email: "komdir@rtrf.ru",
  },
  {
    fullName: {
      ru: "Сучков Александр Алексеевич",
      uz: "Suchkov Aleksandr Alekseevich",
      en: "Suchkov Aleksandr Alekseevich",
    },
    position: {
      ru: "Коммерческий директор",
      uz: "Tijorat direktori",
      en: "Commercial Director",
    },
    phone: "8 (831) 225-00-55",
    email: "sale@rtrf.ru",
  },
  {
    fullName: {
      ru: "Ширдин Михаил Васильевич",
      uz: "Shirdin Mixail Vasilevich",
      en: "Shirdin Mixail Vasilevich",
    },
    position: {
      ru: "Руководитель отдела продаж",
      uz: "Savdo bo'limi boshlig'i",
      en: "Head of Sales Department",
    },
    phone: "8 8312 250055 доб. 202",
    mobile: "8 952 446-69-74",
    email: "rop@rtrf.ru",
  },
  {
    fullName: {
      ru: "Савенко Екатерина Юрьевна",
      uz: "Savenko Yekaterina Yurevna",
      en: "Savenko Yekaterina Yurevna",
    },
    position: {
      ru: "Менеджер по продажам",
      uz: "Savdo menejeri",
      en: "Sales Manager",
    },
    phone: "8 8312 250055 доб. 214",
    email: "RK@rtrf.ru",
  },
  {
    fullName: {
      ru: "Сергеева Юлия Юрьевна",
      uz: "Sergeeva Yuliya Yurevna",
      en: "Sergeeva Yuliya Yurevna",
    },
    position: {
      ru: "Менеджер по продажам",
      uz: "Savdo menejeri",
      en: "Sales Manager",
    },
    phone: "8 8312 250055 доб. 215",
    email: "sale4@rtrf.ru",
  },
  {
    fullName: {
      ru: "Конев Максим Анатольевич",
      uz: "Konev Maksim Anatolevich",
      en: "Konev Maksim Anatolevich",
    },
    position: {
      ru: "Руководитель направления развития дилерской сети",
      uz: "Diler tarmog'ini rivojlantirish yo'nalishi rahbari",
      en: "Head of Dealer Network Development",
    },
    phone: "8 8312 250055 доб. 213",
    mobile: "8 930 270-37-28",
    email: "sale3@rtrf.ru",
  },
  {
    fullName: {
      ru: "Киселёв Иван Александрович",
      uz: "Kiselyov Ivan Aleksandrovich",
      en: "Kiselyov Ivan Aleksandrovich",
    },
    position: {
      ru: "Руководитель отдела по сертификации ООО «РусТрак»",
      uz: "\"RusTrak\" MChJ sertifikatlashtirish bo'limi boshlig'i",
      en: "Head of Certification Department of RusTrak LLC",
    },
    phone: "8 8312 250055 доб. 212",
    mobile: "8 953 415-77-42",
    email: "sale2@rtrf.ru",
  },
  {
    fullName: {
      ru: "Шалявин Дмитрий Леонидович",
      uz: "Shalyavin Dmitriy Leonidovich",
      en: "Shalyavin Dmitriy Leonidovich",
    },
    position: {
      ru: "Главный конструктор",
      uz: "Bosh konstruktor",
      en: "Chief Designer",
    },
    phone: "8 8312 250055 доб. 701",
    email: "kb@rtrf.ru",
  },
  {
    fullName: {
      ru: "Ярилин Александр Валерьевич",
      uz: "Yarilin Aleksandr Valerevich",
      en: "Yarilin Aleksandr Valerevich",
    },
    position: {
      ru: "Инженер по гарантии",
      uz: "Kafolat bo'yicha muhandis",
      en: "Warranty Engineer",
    },
    phone: "8 8312 250055 доб. 610",
    email: "kb1@rtrf.ru",
  },
  {
    fullName: {
      ru: "Муреев Александр Евгеньевич",
      uz: "Mureev Aleksandr Evgenevich",
      en: "Mureev Aleksandr Evgenevich",
    },
    position: {
      ru: "Начальник ОТК",
      uz: "Texnik nazorat bo'limi boshlig'i",
      en: "Head of Quality Control Department",
    },
    phone: "8 8312 250055 доб. 601",
    mobile: "8 953 415-41-71",
    email: "OTK@rtrf.ru",
  },
  {
    fullName: {
      ru: "Иванов Сергей Иванович",
      uz: "Ivanov Sergey Ivanovich",
      en: "Ivanov Sergey Ivanovich",
    },
    position: {
      ru: "Руководитель отдела снабжения",
      uz: "Ta'minot bo'limi boshlig'i",
      en: "Head of Supply Department",
    },
    phone: "8 8312 250055 доб. 401",
    mobile: "8 951 915-14-23",
    email: "snab@rtrf.ru",
  },
];
